### PR TITLE
PHP8 support

### PR DESCRIPTION
**Pull request by Matth--**
- Added PHP 8 as supported version
- Twig was locked to version 3.0.0
- Changed travis configuration so multiple versions of Symfony get tested against multiple PHP versions
- Composer cache fixed in travis
- Fixed ObjectManager not found warning

### CODE REVIEW

**Comment by Matth--** [comment]
@Bukashk0zzz @thecatontheflat

Quick question

I added PHP 8 as a possible PHP version (works out of the box! 👍 ) but PHPUnit version 8 is not capable of generating code coverage reports on PHP 8. Do you want me to upgrade the PHPUnit version as well? The only problem there is that PHPUnit 9 supports PHP 7.3 and up.

This could be considered a BC break so I don't know if this PR should already fix that.

**Comment by Bukashk0zzz** [comment]
In my opinion in any case better make separate PR for PHPUnit update. 

I can merge this PR as is.

**Comment by Bukashk0zzz** [comment]
And thank you for great job!

**Comment by Matth--** [comment]
@Bukashk0zzz 

Ok I squashed the commits and this PR is no longer a WIP.

**Pull request merged**
