### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by Bukashk0zzz**
Hi,

Pull request contains:
- Codestyle rules
- First test and settings
- Fixed dependencies
- Small bug fixes
- Update license now it correct in composer and GitHub
- Add support Symfony 4 and Symphony Flex
- Dropped support PHP < 7.1 and Symfony 3.3

If you agree with this changes. It will be good if you give me write access to this repo. I will add more linters for this project + will add some checks in configuration.

If you think so big changes not good idea thats ok. I will do all the things in my fork.

### CODE REVIEW

**Comment by thecatontheflat** [comment]
Hey! This looks awesome, thank you so much for taking your time and creating the PR!

The only concern I have is escaping the native functions such as `json_encode()`, `explode()`, `count()` etc. I think it contributes to the worse readability. 

Is specifying global namespace for those functions really necessary?

**Comment by Bukashk0zzz** [comment]
@thecatontheflat Starting from 7.1 this is important for I-cache optimization

**Comment by thecatontheflat** [comment]
Thanks a lot for this!

**Comment by thecatontheflat** [comment]
Created 2.0.0 tag

**Comment by Bukashk0zzz** [comment]
@thecatontheflat Can you please add 
- https://travis-ci.org for tests
- https://scrutinizer-ci.com for code inspection
- https://insight.sensiolabs.com for symfony style chek
- https://codecov.io for code coverage?

Your repo not in organization so I can't do this. 
This not take much time but repo will looks much better.
When you registered this repo in this tools I will add badges and update readme.
Thanks.

**Comment by Bukashk0zzz** [comment]
Also thanks for merging.

**Comment by thecatontheflat** [comment]
@Bukashk0zzz Could you do this if I added you to the co-owners of this repo?

**Comment by Bukashk0zzz** [comment]
https://travis-ci.org -- not sure but others think yes.

**Comment by thecatontheflat** [comment]
Activated this project on Travis, sent you a Collaborator's invite

Cheers!

**Comment by Bukashk0zzz** [comment]
@thecatontheflat Thank you.

**Pull request merged**
