### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by Bukashk0zzz**

### CODE REVIEW

**Comment by Bukashk0zzz** [comment]
@thecatontheflat Can you also remove 2 from here

https://monosnap.com/file/bEY7BKJlkzOiY94HGm8kj97IkgPzaB

**Comment by thecatontheflat** [comment]
Done. Thanks!

**Comment by Bukashk0zzz** [comment]
And how I see SensioLabs work not correct it must be now in pull req check but there are no check from them.

**Comment by Bukashk0zzz** [comment]
@thecatontheflat So you will look what wrong with sense labs?

**Comment by thecatontheflat** [comment]
Yeah I'll check it

**Pull request merged**
