### PR TITLE
Use symfony/http-client, drop 4.4 support and php < 8.0

### PR DESCRIPTION
**Pull request by Matth--**
- Made it testable
- Default setUp in services

### CODE REVIEW

**Comment by Matth--** [comment]
@Bukashk0zzz @thecatontheflat 

This might need a review as this is a big breaking change for 4.0 🙂

**Comment by Bukashk0zzz** [comment]
You done great job @Matth-- 

Few things that I can propose as tracking changes allowed:
1) Migrate from Guzzle to Symfony http client. Reasons: we already use Symfony components, it has a nice debugger tab, rest-client reverted.
2) Remove support of PHP 7.4 Reasons: will allow using of short declarations of properties and type-hint everything. 7.4 will EOL in the next 11 months. https://www.php.net/supported-versions.php
3) Drop support of Symphony 4

**Comment by Bukashk0zzz** [comment]
Great idea add AtlassianRestClientInterface 
I think this can save a lot of time for someone :)

**Comment by Bukashk0zzz** [comment]
As for me now, with Symfony HTTP Client, all looks cleaner. Good job.

**Pull request merged**
