### PR TITLE
Extract TenantStorageInterface to avoid direct doctrine dependency

### PR DESCRIPTION
**Pull request by WaylandAce**
Avoid direct doctrine dependency and allow replace tenant storage implementation

### CODE REVIEW

**Comment by Bukashk0zzz** [comment]
@WaylandAce Thanks for PR.
I think creating storage abstraction a very good idea. But this is a huge BC. 
I don't see any reasons to not merge this and create a new version. @Matth-- Maybe you have some thoughts?

**Comment by Matth--** [comment]
@Bukashk0zzz  I feel like this pull request only adds an interface instead of calling doctrine directly. The exact behavior is still the same so I don't think this will cause BC issues and will improve extensibility.

I will be able to review the code later this week or next week if you want me to 🙂 

@WaylandAce I like the changes here! Could you rebase to master?

**Comment by Bukashk0zzz** [comment]
@WaylandAce Can you please fix code style https://github.com/thecatontheflat/atlassian-connect-bundle/pull/50/checks?check_run_id=2737247103

When this PR pass all tests I will merge it

**Comment by Matth--** [comment]
Closing this in favor of #70. Thanks for the initial PR!

**Pull request closed without merging**
