### PR TITLE
Use Github actions in favour of Travis

### PR DESCRIPTION
**Pull request by Matth--**
The jobs start and complete faster.

### CODE REVIEW

**Comment by Matth--** [comment]
@thecatontheflat @Bukashk0zzz 
Tested the actions on my fork. They all work at the moment
Also added the codecov action but could not test that one out on my fork 🙂

**Comment by Bukashk0zzz** [comment]
Look very good. I will try to enable actions but not sure if have enough rights.

**Comment by Bukashk0zzz** [comment]
look like everything good https://github.com/thecatontheflat/atlassian-connect-bundle/actions/runs/605277061

**Comment by Matth--** [comment]
Awesome!

**Pull request merged**
